version: '3.8'
services:
  eureka-server:
    image: jgavirias13/eurekaserver:v1
    ports:
      - 8761:8761
    networks:
      - microservices
  books:
    image: jgavirias13/booksapp:v3
    networks:
      - microservices
    depends_on:
      - eureka-server
  recommendations:
    image: jgavirias13/recommendationsapp:v1
    depends_on:
      - eureka-server
    networks:
      - microservices
  gateway:
    image: jgavirias13/gateway:v1
    depends_on:
      - eureka-server
    ports:
      - 8082:8082
    networks:
      - microservices
  admin:
    image: jgavirias13/adminapp:v1
    depends_on:
      - eureka-server
    ports:
      - 8083:8083
    networks:
      - microservices
networks:
  microservices:
    driver: bridge
